### ISSUE TITLE
Resource form returns to Document tab on save.

### ISSUE THREAD

**Issue by tehsquidge** [Mark-H/VersionX2#74] opened 2015-01-12 15:49 UTC
Hi,

I've noticed that after installing VersionX that when saving a Document the page returns to the Document tab. Without VersionX installed the user is not move from the tab they're currently on (for example the Template Variable tab). This is just a slight annoyance but it would be good to fix if possible.

I've tested this on a fresh install of MODX and the latest VersionX from the package manager. 

thanks,
Liam

**Comment by Mark-H** [comment] 2015-05-15 14:55
I'd love to see this fixed as well, but to be honest I'm not exactly sure why this is happening. If anyone knows.. let me know.

**Comment by Mark-H** [comment] 2016-03-07 22:50
Note to self: changing the way the tab is added by using `Ext.override` instead of `tabpanel.add` might do the trick. Though I'm not 100% sure that's the cause.

**Comment by Mark-H** [comment] 2019-08-22 10:36
Fixed in 2.2.2. Turns out `MODx.addTab()` calls `tabs.setActiveTab(0);` and because the tab got added in a `MODx.on('ready', callback);` callback, that got executed repeatedly after a save.

**Closed** 2019-08-22 10:36 UTC
Labels: 2 - Major
